
appname = MID_SPIKE
httpport = 8082
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 
API_CRUD = localhost:8088
API_CRUD_FINCA = localhost:8086
API_CRUD_SENSOR = localhost:8087
API_CRUD_CULTIVO = localhost:8085
