
appname = MID_SPIKE
httpport = 8082
runmode = dev
autorender = false
copyrequestbody = true
EnableDocs = true
sqlconn = 
<<<<<<< HEAD
API_CRUD = localhost:8087
=======
API_CRUD = localhost:8088
API_CRUD_FINCA = localhost:8086
>>>>>>> 78cd5e00d6587a3492928b10f609d22e433b7c16
